SpartaIMSEng24/Controllers/SpartanUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SpartaIMSEng24.Data;
using SpartaIMSEng24.Models;

namespace SpartaIMSEng24.Controllers
{
    public class SpartanUserController : Controller
    {
        private readonly SpartaIMSContext _context;

        public SpartanUserController(SpartaIMSContext context)
        {
            _context = context;
        }

        // GET: SpartanUser
        public async Task<IActionResult> Index()
        {
            var spartaIMSContext = _context.SpartanUsers.Include(s => s.Cohort).Include(s => s.JobRole);
            return View(await spartaIMSContext.ToListAsync());
        }

        // GET: SpartanUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spartanUser = await _context.SpartanUsers
                .Include(s => s.Cohort)
                .Include(s => s.JobRole)
                .FirstOrDefaultAsync(m => m.SpartanID == id);
            if (spartanUser == null)
            {
                return NotFound();
            }

            return View(spartanUser);
        }

        // GET: SpartanUser/Create
        public IActionResult Create()
        {
            ViewData["CohortID"] = new SelectList(_context.Cohorts, "CohortID", "CohortID");
            ViewData["JobRoleID"] = new SelectList(_context.JobRoles, "JobRoleID", "JobRoleID");
            return View();
        }

        // POST: SpartanUser/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SpartanID,FirstName,LastName,Email,Password,FullName,CohortID,JobRoleID")] SpartanUser spartanUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spartanUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CohortID"] = new SelectList(_context.Cohorts, "CohortID", "CohortID", spartanUser.CohortID);
            ViewData["JobRoleID"] = new SelectList(_context.JobRoles, "JobRoleID", "JobRoleID", spartanUser.JobRoleID);
            return View(spartanUser);
        }

        // GET: SpartanUser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spartanUser = await _context.SpartanUsers.FindAsync(id);
            if (spartanUser == null)
            {
                return NotFound();
            }
            ViewData["CohortID"] = new SelectList(_context.Cohorts, "CohortID", "CohortID", spartanUser.CohortID);
            ViewData["JobRoleID"] = new SelectList(_context.JobRoles, "JobRoleID", "JobRoleID", spartanUser.JobRoleID);
            return View(spartanUser);
        }

        // POST: SpartanUser/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpartanID,FirstName,LastName,Email,Password,FullName,CohortID,JobRoleID")] SpartanUser spartanUser)
        {
            if (id != spartanUser.SpartanID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spartanUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpartanUserExists(spartanUser.SpartanID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CohortID"] = new SelectList(_context.Cohorts, "CohortID", "CohortID", spartanUser.CohortID);
            ViewData["JobRoleID"] = new SelectList(_context.JobRoles, "JobRoleID", "JobRoleID", spartanUser.JobRoleID);
            return View(spartanUser);
        }

        // GET: SpartanUser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spartanUser = await _context.SpartanUsers
                .Include(s => s.Cohort)
                .Include(s => s.JobRole)
                .FirstOrDefaultAsync(m => m.SpartanID == id);
            if (spartanUser == null)
            {
                return NotFound();
            }

            return View(spartanUser);
        }

        // POST: SpartanUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var spartanUser = await _context.SpartanUsers.FindAsync(id);
            _context.SpartanUsers.Remove(spartanUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpartanUserExists(int id)
        {
            return _context.SpartanUsers.Any(e => e.SpartanID == id);
        }
    }
}

SpartaIMSEng24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpartaIMSEng24</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SpartaIMSEng24</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="SpartanUser" asp-action="Index">Sparta Users</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SpartaIMSEng24</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>